# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ioInterface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ioInterface(object):
    def setupUi(self, ioInterface):
        ioInterface.setObjectName("ioInterface")
        ioInterface.setEnabled(True)
        ioInterface.resize(834, 424)
        ioInterface.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        ioInterface.setFont(font)
        ioInterface.setFocusPolicy(QtCore.Qt.TabFocus)
        ioInterface.setAutoFillBackground(True)
        ioInterface.setTabShape(QtWidgets.QTabWidget.Rounded)
        ioInterface.setIconSize(QtCore.QSize(40, 16))
        self.Outputs = QtWidgets.QWidget()
        self.Outputs.setObjectName("Outputs")
        self.Output_Title = QtWidgets.QLabel(self.Outputs)
        self.Output_Title.setGeometry(QtCore.QRect(30, 10, 141, 16))
        self.Output_Title.setObjectName("Output_Title")
        self.lcd_15 = QtWidgets.QLCDNumber(self.Outputs)
        self.lcd_15.setGeometry(QtCore.QRect(80, 50, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_15.setFont(font)
        self.lcd_15.setToolTipDuration(0)
        self.lcd_15.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.lcd_15.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_15.setLineWidth(1)
        self.lcd_15.setMidLineWidth(0)
        self.lcd_15.setDigitCount(1)
        self.lcd_15.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_15.setProperty("value", 0.0)
        self.lcd_15.setProperty("intValue", 0)
        self.lcd_15.setObjectName("lcd_15")
        self.btnFwd = QtWidgets.QPushButton(self.Outputs)
        self.btnFwd.setGeometry(QtCore.QRect(130, 110, 51, 51))
        self.btnFwd.setObjectName("btnFwd")
        self.btnStop = QtWidgets.QPushButton(self.Outputs)
        self.btnStop.setGeometry(QtCore.QRect(70, 110, 51, 51))
        self.btnStop.setObjectName("btnStop")
        self.btnRev = QtWidgets.QPushButton(self.Outputs)
        self.btnRev.setGeometry(QtCore.QRect(10, 110, 51, 51))
        self.btnRev.setObjectName("btnRev")
        self.btnReset = QtWidgets.QPushButton(self.Outputs)
        self.btnReset.setGeometry(QtCore.QRect(70, 170, 51, 51))
        self.btnReset.setObjectName("btnReset")
        self.lcd_idxcounter = QtWidgets.QLCDNumber(self.Outputs)
        self.lcd_idxcounter.setGeometry(QtCore.QRect(130, 50, 91, 41))
        self.lcd_idxcounter.setObjectName("lcd_idxcounter")
        self.btnCONVEYOR_THREAD = QtWidgets.QPushButton(self.Outputs)
        self.btnCONVEYOR_THREAD.setGeometry(QtCore.QRect(210, 110, 111, 101))
        self.btnCONVEYOR_THREAD.setCheckable(True)
        self.btnCONVEYOR_THREAD.setObjectName("btnCONVEYOR_THREAD")
        self.btnESTOP = QtWidgets.QPushButton(self.Outputs)
        self.btnESTOP.setGeometry(QtCore.QRect(330, 110, 111, 101))
        self.btnESTOP.setObjectName("btnESTOP")
        self.btnEnable = QtWidgets.QCheckBox(self.Outputs)
        self.btnEnable.setGeometry(QtCore.QRect(0, 230, 121, 91))
        self.btnEnable.setBaseSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnEnable.setFont(font)
        self.btnEnable.setStyleSheet("QCheckBox::indicator {\n"
"width: 20px;\n"
"height: 20px;\n"
"}\n"
"")
        self.btnEnable.setIconSize(QtCore.QSize(28, 28))
        self.btnEnable.setTristate(False)
        self.btnEnable.setObjectName("btnEnable")
        self.btnEnableDispense = QtWidgets.QCheckBox(self.Outputs)
        self.btnEnableDispense.setGeometry(QtCore.QRect(140, 230, 121, 91))
        self.btnEnableDispense.setBaseSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnEnableDispense.setFont(font)
        self.btnEnableDispense.setStyleSheet("QCheckBox::indicator {\n"
"width: 20px;\n"
"height: 20px;\n"
"}\n"
"")
        self.btnEnableDispense.setIconSize(QtCore.QSize(28, 28))
        self.btnEnableDispense.setTristate(False)
        self.btnEnableDispense.setObjectName("btnEnableDispense")
        self.btnEnableEject = QtWidgets.QCheckBox(self.Outputs)
        self.btnEnableEject.setGeometry(QtCore.QRect(290, 230, 121, 91))
        self.btnEnableEject.setBaseSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnEnableEject.setFont(font)
        self.btnEnableEject.setStyleSheet("QCheckBox::indicator {\n"
"width: 20px;\n"
"height: 20px;\n"
"}\n"
"")
        self.btnEnableEject.setIconSize(QtCore.QSize(28, 28))
        self.btnEnableEject.setTristate(False)
        self.btnEnableEject.setObjectName("btnEnableEject")
        self.lblConveyor_FSM = QtWidgets.QLabel(self.Outputs)
        self.lblConveyor_FSM.setGeometry(QtCore.QRect(230, 220, 47, 13))
        self.lblConveyor_FSM.setObjectName("lblConveyor_FSM")
        ioInterface.addTab(self.Outputs, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnDispense = QtWidgets.QPushButton(self.tab)
        self.btnDispense.setGeometry(QtCore.QRect(20, 40, 111, 111))
        self.btnDispense.setObjectName("btnDispense")
        self.btnGetStatus = QtWidgets.QPushButton(self.tab)
        self.btnGetStatus.setGeometry(QtCore.QRect(140, 40, 111, 111))
        self.btnGetStatus.setObjectName("btnGetStatus")
        self.lblDispenserStatus = QtWidgets.QLabel(self.tab)
        self.lblDispenserStatus.setGeometry(QtCore.QRect(280, 40, 481, 101))
        font = QtGui.QFont()
        font.setPointSize(34)
        self.lblDispenserStatus.setFont(font)
        self.lblDispenserStatus.setObjectName("lblDispenserStatus")
        self.btnReset_2 = QtWidgets.QPushButton(self.tab)
        self.btnReset_2.setGeometry(QtCore.QRect(20, 160, 111, 111))
        self.btnReset_2.setObjectName("btnReset_2")
        self.btnInit = QtWidgets.QPushButton(self.tab)
        self.btnInit.setGeometry(QtCore.QRect(140, 160, 111, 111))
        self.btnInit.setObjectName("btnInit")
        ioInterface.addTab(self.tab, "")
        self.Inputs = QtWidgets.QWidget()
        self.Inputs.setObjectName("Inputs")
        self.Input_Status = QtWidgets.QListWidget(self.Inputs)
        self.Input_Status.setGeometry(QtCore.QRect(510, 20, 271, 251))
        self.Input_Status.setObjectName("Input_Status")
        self.lcd_65 = QtWidgets.QLCDNumber(self.Inputs)
        self.lcd_65.setGeometry(QtCore.QRect(90, 80, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_65.setFont(font)
        self.lcd_65.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_65.setLineWidth(1)
        self.lcd_65.setMidLineWidth(0)
        self.lcd_65.setDigitCount(1)
        self.lcd_65.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_65.setProperty("value", 0.0)
        self.lcd_65.setProperty("intValue", 0)
        self.lcd_65.setObjectName("lcd_65")
        self.lcd_66 = QtWidgets.QLCDNumber(self.Inputs)
        self.lcd_66.setGeometry(QtCore.QRect(90, 290, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_66.setFont(font)
        self.lcd_66.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_66.setLineWidth(1)
        self.lcd_66.setMidLineWidth(0)
        self.lcd_66.setDigitCount(1)
        self.lcd_66.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_66.setProperty("value", 0.0)
        self.lcd_66.setProperty("intValue", 0)
        self.lcd_66.setObjectName("lcd_66")
        self.lcd_81 = QtWidgets.QLCDNumber(self.Inputs)
        self.lcd_81.setGeometry(QtCore.QRect(130, 20, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_81.setFont(font)
        self.lcd_81.setToolTipDuration(0)
        self.lcd_81.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.lcd_81.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_81.setLineWidth(1)
        self.lcd_81.setMidLineWidth(0)
        self.lcd_81.setDigitCount(1)
        self.lcd_81.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_81.setProperty("value", 0.0)
        self.lcd_81.setProperty("intValue", 0)
        self.lcd_81.setObjectName("lcd_81")
        self.btnUP = QtWidgets.QPushButton(self.Inputs)
        self.btnUP.setGeometry(QtCore.QRect(170, 80, 50, 50))
        self.btnUP.setCheckable(False)
        self.btnUP.setAutoRepeat(False)
        self.btnUP.setObjectName("btnUP")
        self.btnDN = QtWidgets.QPushButton(self.Inputs)
        self.btnDN.setGeometry(QtCore.QRect(170, 280, 50, 50))
        self.btnDN.setCheckable(False)
        self.btnDN.setObjectName("btnDN")
        self.lcd_0 = QtWidgets.QLCDNumber(self.Inputs)
        self.lcd_0.setGeometry(QtCore.QRect(750, 300, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_0.setFont(font)
        self.lcd_0.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_0.setLineWidth(1)
        self.lcd_0.setMidLineWidth(0)
        self.lcd_0.setDigitCount(1)
        self.lcd_0.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_0.setProperty("value", 0.0)
        self.lcd_0.setProperty("intValue", 0)
        self.lcd_0.setObjectName("lcd_0")
        self.btnAUTO_THREAD = QtWidgets.QPushButton(self.Inputs)
        self.btnAUTO_THREAD.setGeometry(QtCore.QRect(10, 180, 111, 51))
        self.btnAUTO_THREAD.setCheckable(False)
        self.btnAUTO_THREAD.setObjectName("btnAUTO_THREAD")
        self.servoStart = QtWidgets.QSlider(self.Inputs)
        self.servoStart.setGeometry(QtCore.QRect(280, 50, 211, 51))
        self.servoStart.setMinimum(150)
        self.servoStart.setMaximum(600)
        self.servoStart.setOrientation(QtCore.Qt.Horizontal)
        self.servoStart.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.servoStart.setObjectName("servoStart")
        self.servoStop = QtWidgets.QSlider(self.Inputs)
        self.servoStop.setGeometry(QtCore.QRect(280, 90, 211, 51))
        self.servoStop.setMinimum(150)
        self.servoStop.setMaximum(600)
        self.servoStop.setProperty("value", 600)
        self.servoStop.setOrientation(QtCore.Qt.Horizontal)
        self.servoStop.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.servoStop.setObjectName("servoStop")
        self.servoStartAngle = QtWidgets.QLCDNumber(self.Inputs)
        self.servoStartAngle.setGeometry(QtCore.QRect(430, 30, 64, 23))
        self.servoStartAngle.setDigitCount(3)
        self.servoStartAngle.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.servoStartAngle.setProperty("value", 150.0)
        self.servoStartAngle.setObjectName("servoStartAngle")
        self.servoStopAngle = QtWidgets.QLCDNumber(self.Inputs)
        self.servoStopAngle.setGeometry(QtCore.QRect(430, 130, 64, 23))
        self.servoStopAngle.setDigitCount(3)
        self.servoStopAngle.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.servoStopAngle.setProperty("value", 600.0)
        self.servoStopAngle.setObjectName("servoStopAngle")
        self.btnEject = QtWidgets.QPushButton(self.Inputs)
        self.btnEject.setGeometry(QtCore.QRect(170, 20, 51, 51))
        self.btnEject.setObjectName("btnEject")
        self.Input_Title_2 = QtWidgets.QLabel(self.Inputs)
        self.Input_Title_2.setGeometry(QtCore.QRect(280, 30, 131, 16))
        self.Input_Title_2.setObjectName("Input_Title_2")
        self.CycleCountBin1 = QtWidgets.QLCDNumber(self.Inputs)
        self.CycleCountBin1.setGeometry(QtCore.QRect(10, 230, 111, 41))
        self.CycleCountBin1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.CycleCountBin1.setProperty("value", 0.0)
        self.CycleCountBin1.setProperty("intValue", 0)
        self.CycleCountBin1.setObjectName("CycleCountBin1")
        self.bin1Level = QtWidgets.QSlider(self.Inputs)
        self.bin1Level.setGeometry(QtCore.QRect(130, 80, 41, 251))
        self.bin1Level.setAutoFillBackground(True)
        self.bin1Level.setStyleSheet("color: rgb(255, 85, 0);")
        self.bin1Level.setMaximum(6000)
        self.bin1Level.setOrientation(QtCore.Qt.Vertical)
        self.bin1Level.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.bin1Level.setTickInterval(10)
        self.bin1Level.setObjectName("bin1Level")
        self.label = QtWidgets.QLabel(self.Inputs)
        self.label.setGeometry(QtCore.QRect(80, 60, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Inputs)
        self.label_2.setGeometry(QtCore.QRect(90, 340, 47, 13))
        self.label_2.setObjectName("label_2")
        self.bin1Level_set = QtWidgets.QDial(self.Inputs)
        self.bin1Level_set.setGeometry(QtCore.QRect(270, 220, 111, 111))
        self.bin1Level_set.setMinimum(-700)
        self.bin1Level_set.setMaximum(700)
        self.bin1Level_set.setObjectName("bin1Level_set")
        self.bin1Level_target = QtWidgets.QLCDNumber(self.Inputs)
        self.bin1Level_target.setGeometry(QtCore.QRect(270, 170, 111, 51))
        self.bin1Level_target.setObjectName("bin1Level_target")
        self.btnMANUAL_THREAD = QtWidgets.QPushButton(self.Inputs)
        self.btnMANUAL_THREAD.setGeometry(QtCore.QRect(390, 230, 111, 101))
        self.btnMANUAL_THREAD.setCheckable(False)
        self.btnMANUAL_THREAD.setObjectName("btnMANUAL_THREAD")
        self.progressBar = QtWidgets.QProgressBar(self.Inputs)
        self.progressBar.setGeometry(QtCore.QRect(230, 80, 16, 251))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setMinimum(70)
        self.progressBar.setMaximum(470)
        self.progressBar.setProperty("value", 69)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setObjectName("progressBar")
        self.lcd_82 = QtWidgets.QLCDNumber(self.Inputs)
        self.lcd_82.setGeometry(QtCore.QRect(90, 20, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_82.setFont(font)
        self.lcd_82.setToolTipDuration(0)
        self.lcd_82.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.lcd_82.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_82.setLineWidth(1)
        self.lcd_82.setMidLineWidth(0)
        self.lcd_82.setDigitCount(1)
        self.lcd_82.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_82.setProperty("value", 0.0)
        self.lcd_82.setProperty("intValue", 0)
        self.lcd_82.setObjectName("lcd_82")
        self.lblBin1_FSM = QtWidgets.QLabel(self.Inputs)
        self.lblBin1_FSM.setGeometry(QtCore.QRect(10, 280, 47, 13))
        self.lblBin1_FSM.setObjectName("lblBin1_FSM")
        self.tofDistance = QtWidgets.QLCDNumber(self.Inputs)
        self.tofDistance.setGeometry(QtCore.QRect(190, 340, 51, 31))
        self.tofDistance.setObjectName("tofDistance")
        self.btnEnableCycle = QtWidgets.QCheckBox(self.Inputs)
        self.btnEnableCycle.setGeometry(QtCore.QRect(10, 140, 111, 41))
        self.btnEnableCycle.setBaseSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnEnableCycle.setFont(font)
        self.btnEnableCycle.setStyleSheet("QCheckBox::indicator {\n"
"width: 20px;\n"
"height: 20px;\n"
"}\n"
"")
        self.btnEnableCycle.setIconSize(QtCore.QSize(28, 28))
        self.btnEnableCycle.setTristate(False)
        self.btnEnableCycle.setObjectName("btnEnableCycle")
        self.topLevel = QtWidgets.QScrollBar(self.Inputs)
        self.topLevel.setGeometry(QtCore.QRect(250, 80, 16, 251))
        self.topLevel.setMaximum(600)
        self.topLevel.setOrientation(QtCore.Qt.Vertical)
        self.topLevel.setObjectName("topLevel")
        self.tofDistanceSP = QtWidgets.QLCDNumber(self.Inputs)
        self.tofDistanceSP.setGeometry(QtCore.QRect(250, 340, 51, 31))
        self.tofDistanceSP.setObjectName("tofDistanceSP")
        ioInterface.addTab(self.Inputs, "")

        self.retranslateUi(ioInterface)
        ioInterface.setCurrentIndex(2)
        self.servoStart.valueChanged['int'].connect(self.servoStartAngle.display)
        self.servoStop.valueChanged['int'].connect(self.servoStopAngle.display)
        self.btnESTOP.clicked.connect(ioInterface.close)
        self.bin1Level_set.valueChanged['int'].connect(self.bin1Level_target.display)
        self.progressBar.valueChanged['int'].connect(self.tofDistance.display)
        self.topLevel.valueChanged['int'].connect(self.tofDistanceSP.display)
        QtCore.QMetaObject.connectSlotsByName(ioInterface)

    def retranslateUi(self, ioInterface):
        _translate = QtCore.QCoreApplication.translate
        ioInterface.setWindowTitle(_translate("ioInterface", "Rpi io interface"))
        self.Output_Title.setText(_translate("ioInterface", "Conveyor control"))
        self.lcd_15.setToolTip(_translate("ioInterface", "Card stuck sensor"))
        self.btnFwd.setText(_translate("ioInterface", "FWD"))
        self.btnStop.setText(_translate("ioInterface", "STOP"))
        self.btnRev.setText(_translate("ioInterface", "REV"))
        self.btnReset.setText(_translate("ioInterface", "Reset"))
        self.btnCONVEYOR_THREAD.setText(_translate("ioInterface", "Conveyor thread"))
        self.btnESTOP.setText(_translate("ioInterface", "Estop"))
        self.btnEnable.setText(_translate("ioInterface", "Enable"))
        self.btnEnableDispense.setText(_translate("ioInterface", "Dispense"))
        self.btnEnableEject.setText(_translate("ioInterface", "Eject"))
        self.lblConveyor_FSM.setText(_translate("ioInterface", "State"))
        ioInterface.setTabText(ioInterface.indexOf(self.Outputs), _translate("ioInterface", "Conveyor"))
        self.btnDispense.setText(_translate("ioInterface", "Dispense"))
        self.btnGetStatus.setText(_translate("ioInterface", "Get status"))
        self.lblDispenserStatus.setText(_translate("ioInterface", "Status..."))
        self.btnReset_2.setText(_translate("ioInterface", "Reset"))
        self.btnInit.setText(_translate("ioInterface", "Initialize"))
        ioInterface.setTabText(ioInterface.indexOf(self.tab), _translate("ioInterface", "Dispenser"))
        self.lcd_81.setToolTip(_translate("ioInterface", "Card stuck sensor"))
        self.btnUP.setText(_translate("ioInterface", "UP"))
        self.btnDN.setText(_translate("ioInterface", "DN"))
        self.btnAUTO_THREAD.setText(_translate("ioInterface", "AUTO Cycle bin1"))
        self.btnEject.setText(_translate("ioInterface", "eject"))
        self.Input_Title_2.setText(_translate("ioInterface", "Servo control"))
        self.label.setText(_translate("ioInterface", "High Limit"))
        self.label_2.setText(_translate("ioInterface", "Low Limit"))
        self.btnMANUAL_THREAD.setText(_translate("ioInterface", "MANUAL bin1"))
        self.lcd_82.setToolTip(_translate("ioInterface", "Card stuck sensor"))
        self.lblBin1_FSM.setText(_translate("ioInterface", "State"))
        self.btnEnableCycle.setText(_translate("ioInterface", "Enabled"))
        ioInterface.setTabText(ioInterface.indexOf(self.Inputs), _translate("ioInterface", "Bins"))

